"""
backend/predictor.py
====================
Real CNN inference pipeline.
Uses model.predict() → true softmax probabilities.
No simulated values — all outputs come from the model.

Label mapping
─────────────
Labels are loaded dynamically from class_names.json (written by train_model.py).
There are NO hardcoded class lists here — see model_loader.get_class_labels().
"""
from __future__ import annotations

import logging
from typing import Any, Optional

import numpy as np

from models.model_loader import get_class_labels, preprocess_image

logger = logging.getLogger(__name__)


def run_inference(
    image_bytes: bytes,
    model,
    tf,
) -> Optional[dict[str, Any]]:
    """
    Run real CNN inference on image bytes.

    Steps:
      1. Load class labels dynamically (from class_names.json)
      2. Preprocess → normalised (1, H, W, 3) batch
      3. model.predict() → softmax probability vector
      4. Validate output shape matches loaded class count
      5. argmax → predicted class
      6. Return structured prediction dict

    Returns None on failure.
    """
    if model is None or tf is None:
        return None

    # ── Step 1: resolve labels from training output ───────────────────────────
    # This call reads class_names.json and caches the result.
    # It will NEVER use a hardcoded list unless the JSON is missing.
    class_labels = get_class_labels()
    num_classes  = len(class_labels)

    # ── Step 2: preprocess ────────────────────────────────────────────────────
    batch = preprocess_image(image_bytes, tf)
    if batch is None:
        return None

    # ── Step 3: inference ─────────────────────────────────────────────────────
    try:
        raw_probs = model.predict(batch, verbose=0)[0]   # shape: (num_classes,)
    except Exception as exc:
        logger.error(f"model.predict() failed: {exc}")
        return None

    raw_probs = np.array(raw_probs, dtype=np.float32)

    # ── Step 4: shape sanity-check ────────────────────────────────────────────
    if raw_probs.shape[0] != num_classes:
        logger.error(
            f"Model output size ({raw_probs.shape[0]}) does not match "
            f"loaded class count ({num_classes}). "
            "Ensure class_names.json was generated by the current training run."
        )
        return None

    # Normalise to sum=1 (guard against floating-point drift)
    raw_probs = raw_probs / (raw_probs.sum() + 1e-9)

    # ── Step 5: top prediction ────────────────────────────────────────────────
    pred_idx   = int(np.argmax(raw_probs))
    prediction = class_labels[pred_idx]        # snake_case internal label
    confidence = float(raw_probs[pred_idx])

    # ── Step 6: ranked probability dict ──────────────────────────────────────
    prob_dict = {
        label: float(raw_probs[i])
        for i, label in enumerate(class_labels)
    }
    prob_dict = dict(sorted(prob_dict.items(), key=lambda x: x[1], reverse=True))

    return {
        "prediction":    prediction,    # e.g. "acne"  (snake_case)
        "confidence":    confidence,
        "probabilities": prob_dict,
        "raw_probs":     raw_probs,     # numpy array, kept for downstream engines
        "pred_idx":      pred_idx,      # integer index, used by Grad-CAM
    }


def extract_ranked_predictions(prob_dict: dict[str, float]) -> tuple[tuple, tuple]:
    """
    Extract primary and secondary predictions from a sorted probability dict.

    Returns:
        primary   = (label, prob)
        secondary = (label, prob)
    """
    items     = list(prob_dict.items())
    primary   = items[0] if len(items) > 0 else ("unknown", 0.0)
    secondary = items[1] if len(items) > 1 else primary
    return primary, secondary